apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: klab
spec:
  selector:
    matchLabels:
      name: mongodb
  serviceName: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        name: mongodb
    spec:
      containers:
      - name: mongodb
        image: registry.cn-shanghai.aliyuncs.com/kcr-3rd/mongo:4
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1
            memory: 4Gi
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db 
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn
---
apiVersion: v1
data:
  username: a2VzY2k=
  password: aGV5d2hhbGU=
kind: Secret
metadata:
  name: mongodb-secret
  namespace: klab
type: Opaque
---
kind: Service
apiVersion: v1
metadata:
  labels:
    name: mongodb
  name: mongodb
  namespace: klab
spec:
  type: NodePort
  ports:
  - name: mongodb
    port: 27017
    targetPort: 27017
    nodePort: 30002
  selector:
    name: mongodb
